#missing code here














































---
apiVersion: v1 
kind: Service
metadata:
  name: stedi-jacob-nodeport
spec:
  selector:
    app: stedi-jacob-dev
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-jacob-certificate
spec:
  domains:
    - jacobcausey.cit262.com
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: stedi-jacob-Ingress
  annotations:
    kubernetes.io/ingress.global.static-ip-name: stedi-jacob-public
    networking.gke.io/managed-certificates: stedi-jacob-certificate
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            services:
              name: stedi-jacob-nodeport
              port:
                number: 80