missing code here














































---
apiVersion: v1 
kind: Service
metadata:
  name: stedi-jacob-nodeport
spec:
  selector:
    app: stedi-jacob-dev
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-jacob-certificate
spec:
  domains:
    - jacobcausey.cit262.com
---
    











